### ISSUE TITLE
[Feature request] Support DataGrid

### ISSUE THREAD

**Issue by q0v0p** [AngryCarrot789/WPFDarkTheme#1]
Hi,

Thank you for a great job.
I would like to use it with Datagrid, so please support it.

Thank you for your consideration.

**Comment by AngryCarrot789** [comment]
will try to do this

**Comment by q0v0p** [comment]
I appreciate it very much!
I'm looking forward to it😆

**Comment by jstevenson72** [comment]
Agreed!  I download and installed, solely for the DataGrid, and it showed up Yellow/Green, lol.

Thanks for the work so far.  If I figure anything out, I'll share it.

**Comment by reddevlab** [comment]
There are news about DataGrid styling?
Thank's and great job!

**Comment by AngryCarrot789** [comment]
ive recently started playing around with the datagrid so hopefully it will be styles very soon :)

**Comment by chrdavis** [comment]
Here is the Data Grid styling if you want it: 
https://gist.github.com/chrdavis/288d743362b963b875832cc493d2cc94

I used some of te WPFDarkTheme code in a separate project and had to implement the Data Grid styling myself.  Should be able to drop it in and only need to change the spelling of some colors.

**Comment by Elgot** [comment]
@chrdavis Swell! Would it be possible to style DataGridCheckBoxColumn and DataGridComboBoxColumn too? A workaround is to use a DataGridTemplateColumn instead, but it would be nice to have all options.

**Comment by AngryCarrot789** [comment]
I styled the data grid for the new theme library. I haven't implemented nor tested the check box feature yet, but hopefully it at least pulls the foreground from the parents
