### ISSUE TITLE
[Feature Request] Menu separator support

### ISSUE THREAD

**Issue by DoctorLogiq** [AngryCarrot789/WPFDarkTheme#2]
Hey man, first of all, this is a fantastic resource and very much appreciated.

I've been after a dark menu style for longer than I care to recall, and finally, here is one that is actually good! Oddly enough you've even used the exact colours that my app is using, so it just fits right in!

Could you be so kind as to add support for <Separator/> within Menus?

Thanks!

**Comment by AngryCarrot789** [comment]
on the readme bit, it explains how to style menus and the separtator because i couldn't figure out an automatic style unfortunately. and there's also a specific separator style specifically for menuitems.
basically, if you have a MenuItem with children MenuItems, you normally have that little arrow on the parent one, so use DropDownMenuItemStyle template. and for all other ones, use the SingleDropDownMenuItem template
and the separator is a style called MenuItemSeparator

**Comment by DoctorLogiq** [comment]
OH, sorry, I forgot to put the tag in a code block so it doesn't show in he request. 

It was supposed to say:
"Could you be so kind as to add support for `<Separator/>` within Menus?"
...my bad!

To make default styles, _don't_ give the style a key (important) and then give it a Setter Property of `OverridesDefaultStyle` with a value of `True` :)

**Comment by AngryCarrot789** [comment]
im not too sure what you mean, do you want to be able to place a separator in the menuitems and not have to give it the `MenuItemSeparator `style? i dont really know how to do that atm, and i did try messing around with `OverridesDefaultStyle` but i cant seem to get anything to work automatically

**Comment by DoctorLogiq** [comment]
Oh, there's already a `MenuItemSeparator` style? That might be what I'm looking for. I was selectively adding the few pieces I needed, instead of the whole theme file, must've missed that.

In my experience, `OverridesDefaultStyle` only works when the style does not have an `x:Key` associated with it.

(Edit) I should specify, this works when you put the template inside a `<Style>`, i.e:
```xaml
<Style TargetType="{x:Type MenuItem}">
    <Setter Property="OverridesDefaultStyle" Value="True"/>
    <Setter Property="Template">
        <Setter.Value>
            <ControlTemplate TargetType="{x:Type MenuItem}">
                ...
            </ControlTemplate>
        </Setter.Value>
    </Setter>
</Style>

```
