### ISSUE TITLE
Support / Rewrite for Avalonia UI

### ISSUE THREAD

**Issue by gaetandezeiraud** [AngryCarrot789/WPFDarkTheme#34]
Can be an interesting move. I see more and more WPF migrating to Avalonia.

But it need rewrite for sure. Because style is managed differently in Avalonia.

**Comment by uno-studio** [comment]
interesting

**Comment by AngryCarrot789** [comment]
I'm considering trying this out, I can't stand the fluent design 😛. I haven't used Avalonia much so it might be a little while until it's ready, I think i'll put it in this repo in a new project

**Comment by AngryCarrot789** [comment]
There's a WIP of this idea. It's incomplete and there are a good number of controls missing but hopefully it's good enough for basic apps. If i remember right there's some sort of numeric up/down control in Avalonia, i haven't themed that yet.

**Comment by uno-studio** [comment]
[https://github.com/AvaloniaUI/Avalonia/tree/master/src/Avalonia.Controls](url)
You can read more here. Did you mean "NumericUpDown"?

**Comment by AngryCarrot789** [comment]
Thanks and yes
