### ISSUE TITLE
[Question] White buttons with white text

### ISSUE THREAD

**Issue by TuTAH1** [AngryCarrot789/WPFDarkTheme#37]
I copy-pasted all references from Themes to my project, copypasted App.xaml's Resources and it works! But the buttons are white with white text by default. Did I miss something out?

**Comment by AngryCarrot789** [comment]
Are any other control styles applied with the dark theme, e.g. list boxes and check boxes?

**Comment by TuTAH1** [comment]
> Are any other control styles applied with the dark theme, e.g. list boxes and check boxes?

Yes, if I add checkbox, it colors matches with black theme

**Comment by AngryCarrot789** [comment]
Not sure what's happening for you then, since those styles being loaded means the button styles should be loaded and the text block styles which have a foreground which is white

**Comment by TuTAH1** [comment]
I found out that I just need to build a project 😅. After that, the buttons in constructor shows as they should
