### ISSUE TITLE
Right Click Window is not changing the theme

### ISSUE THREAD

**Issue by arefmourtada** [AngryCarrot789/WPFDarkTheme#39]
I have added a spell checker to a textbox. When the right click is used, the popup window does follow the theme.
<img width="328" alt="image" src="https://github.com/AngryCarrot789/WPFDarkTheme/assets/34233984/bcbd6df6-c24b-41ac-96e3-c9def69aa215">

**Comment by AngryCarrot789** [comment]
WPF creates a text box's context menu internally. I haven't really looked into how it does that nor if it's even style-able, but I'll see if I can get it to work

**Comment by AngryCarrot789** [comment]
Sorry for the late response but I implemented a default context menu for text boxes a while ago that should solve this
https://github.com/AngryCarrot789/WPFDarkTheme/commit/432c38160c72f2e92e7595b620627dbe756f311a
