### ISSUE TITLE
'[Unknown]' property does not point to a DependencyObject in path '(0).(1)[1].(2)

### ISSUE THREAD

**Issue by moodypascal** [AngryCarrot789/WPFDarkTheme#5]
An unhandled exception of type 'System.InvalidOperationException' occurred in PresentationFramework.dll '[Unknown]' property does not point to a DependencyObject in path '(0).(1)[1].(2)'

Problem occurs when i use datagrid and go over the tiny space that is empty in the first row (for example this grey area): 
![image](https://user-images.githubusercontent.com/10406599/109403824-3486c180-7960-11eb-88dc-e229d1f8ac78.png)

**Comment by AngryCarrot789** [comment]
i havent touched the datagrid yet, not sure how it entirely works nor how to style it. if you remove all the styles i put in (that i forgot to remove lol), it should be ok
